import { Heart, Home, CalendarDays, Smile, Cookie, HandHeart, Video, Clock3, MessageCircleHeart, Bell, Settings, LogOut, Wifi } from 'lucide-react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useSocket } from '../context/SocketContext'
import { useCall } from '../context/CallContext'
import { Button } from './ui'

const nav = [
  ['/', 'Home', Home], ['/cycle', 'Cycle', CalendarDays], ['/mood', 'Mood', Smile], ['/cravings', 'Cravings', Cookie], ['/requests', 'Requests', HandHeart], ['/call', 'Video Call', Video], ['/timeline', 'Our Timeline', Clock3], ['/messages', 'Messages', MessageCircleHeart], ['/notifications', 'Notifications', Bell], ['/settings', 'Settings', Settings],
] as const
export function AppLayout() {
  const { auth, logout } = useAuth(); const { connected } = useSocket(); const { startCall } = useCall(); const navigate = useNavigate()
  const exit = async () => { await logout(); navigate('/login') }
  return <div className="min-h-screen bg-cream text-ink transition-colors dark:bg-[#171317] dark:text-cream"><aside className="fixed inset-y-0 left-0 z-20 hidden w-72 border-r border-wine/10 bg-cream/80 px-5 py-7 backdrop-blur-xl dark:border-cream/10 dark:bg-[#171317]/85 lg:flex lg:flex-col"><div className="mb-10 flex items-center gap-3 px-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-wine text-cream shadow-glow"><Heart size={19} fill="currentColor" /></div><div><p className="font-display text-lg font-semibold">for her</p><p className="text-xs text-ink/50 dark:text-cream/50">a private space for two</p></div></div><nav className="space-y-1">{nav.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => `focus-ring flex items-center gap-3 rounded-2xl px-3 py-3 text-sm font-medium transition ${isActive ? 'bg-wine text-cream shadow-glow' : 'text-ink/65 hover:bg-wine/5 dark:text-cream/65 dark:hover:bg-cream/5'}`}><Icon size={18} />{label}</NavLink>)}</nav><div className="mt-auto"><div className="mb-4 rounded-2xl bg-wine/5 p-4 dark:bg-cream/5"><p className="font-medium">{auth?.user.displayName}</p><p className="mt-1 flex items-center gap-1 text-xs text-ink/55 dark:text-cream/55"><Wifi size={12} className={connected ? 'text-emerald-500' : 'text-amber-500'} /> {connected ? 'Private room connected' : 'Reconnecting…'}</p></div><Button onClick={exit} className="w-full text-ink/70 hover:bg-wine/5 dark:text-cream/70"><LogOut size={16} /> Log out</Button></div></aside><main className="mx-auto min-h-screen max-w-7xl px-5 pb-24 pt-8 sm:px-8 lg:ml-72 lg:px-12 lg:py-10"><div className="mb-6 flex items-center justify-between lg:hidden"><div className="flex items-center gap-2 font-display text-xl"><Heart className="text-wine" fill="currentColor" size={19} /> for her</div><button className="focus-ring rounded-xl p-2 text-wine" onClick={startCall} aria-label="Start video call"><Video size={20} /></button></div><Outlet /></main><nav className="fixed inset-x-0 bottom-0 z-30 flex justify-around border-t border-wine/10 bg-cream/90 px-2 py-2 backdrop-blur-xl dark:border-cream/10 dark:bg-[#171317]/90 lg:hidden">{nav.slice(0, 5).map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => `focus-ring grid place-items-center gap-1 rounded-xl px-2 py-1 text-[10px] ${isActive ? 'text-wine dark:text-[#e9a2b3]' : 'text-ink/55 dark:text-cream/55'}`}><Icon size={18} /><span>{label}</span></NavLink>)}</nav></div>
}
