import { useEffect, useRef, useState, type ReactNode } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Camera, CameraOff, Heart, Mic, MicOff, PhoneOff, RotateCcw, Volume2, VolumeX } from 'lucide-react'
import { useCall } from '../context/CallContext'
import { Button } from './ui'

function StreamVideo({ stream, muted, className }: { stream: MediaStream | null; muted?: boolean; className?: string }) { const ref = useRef<HTMLVideoElement>(null); useEffect(() => { if (ref.current) ref.current.srcObject = stream }, [stream]); return stream ? <video ref={ref} autoPlay playsInline muted={muted} className={`h-full w-full object-cover ${className || ''}`} /> : null }
function elapsed(startedAt?: string | null) { if (!startedAt) return '00:00'; const secs = Math.max(0, Math.floor((Date.now() - new Date(startedAt).getTime()) / 1000)); return `${String(Math.floor(secs / 60)).padStart(2, '0')}:${String(secs % 60).padStart(2, '0')}` }
export function CallOverlay() {
  const call = useCall(); const [duration, setDuration] = useState('00:00'); useEffect(() => { if (call.phase !== 'CONNECTED') return; const timer = window.setInterval(() => setDuration(elapsed(call.call?.startedAt)), 1000); return () => clearInterval(timer) }, [call.call?.startedAt, call.phase])
  const visible = call.phase !== 'IDLE'
  return <AnimatePresence>{visible && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-[#1b1016] p-4 text-cream">
    {call.phase === 'INCOMING' ? <motion.div initial={{ scale: .95, y: 12 }} animate={{ scale: 1, y: 0 }} className="w-full max-w-md rounded-[2rem] border border-cream/10 bg-gradient-to-b from-[#5d2036] to-[#2a1820] p-8 text-center shadow-2xl"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-cream/10"><Heart fill="currentColor" className="text-[#f1a3b2]" size={34} /></div><p className="mt-7 text-sm text-cream/65">Silent video call</p><h2 className="mt-2 font-display text-3xl">{call.peer?.displayName || 'Your love'} wants to call</h2><p className="mt-3 text-sm text-cream/65">Your camera and microphone will stay off until you accept.</p><div className="mt-8 grid grid-cols-2 gap-3"><Button onClick={call.decline} className="bg-cream/10 text-cream hover:bg-cream/20"><PhoneOff size={18} /> Decline</Button><Button onClick={() => void call.accept()} className="bg-[#f0a0b1] text-wine hover:bg-[#ffc1ce]"><Heart size={18} fill="currentColor" /> Accept</Button></div></motion.div> : <div className="relative h-full w-full overflow-hidden rounded-[2rem] bg-[#271720] shadow-2xl">
      <div className="absolute inset-0 grid place-items-center">{call.remoteStream ? <StreamVideo stream={call.remoteStream} className="absolute inset-0" /> : <div className="text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-cream/10 text-3xl"><Heart className="text-[#eaa2b0]" fill="currentColor" /></div><h2 className="mt-5 font-display text-3xl">{call.phase === 'CALLING' ? 'Calling quietly…' : call.phase === 'DECLINED' ? 'Call declined' : call.phase === 'ENDED' ? 'Call ended' : call.phase === 'FAILED' ? 'Call could not connect' : 'Connecting your private call…'}</h2><p className="mt-2 text-sm text-cream/60">{call.error || (call.phase === 'CALLING' ? 'Waiting for them to choose.' : 'No alerts, no recording — just the two of you.')}</p></div>}</div>
      {call.phase === 'CONNECTED' && <p className="absolute left-1/2 top-6 -translate-x-1/2 rounded-full bg-black/30 px-3 py-1 text-xs backdrop-blur">{duration} · Private connection</p>}
      <div className="absolute right-5 top-5 h-36 w-24 overflow-hidden rounded-2xl border border-cream/20 bg-[#4a303d] shadow-xl sm:h-44 sm:w-32">{call.cameraOn ? <StreamVideo stream={call.localStream} muted /> : <div className="grid h-full place-items-center text-center text-xs text-cream/70"><CameraOff size={18} /><span>Camera off</span></div>}</div>
      {(call.phase === 'CONNECTED' || call.phase === 'CONNECTING') && <div className="absolute inset-x-0 bottom-0 flex justify-center gap-2 bg-gradient-to-t from-black/70 to-transparent px-4 pb-7 pt-16"><Control label={call.muted ? 'Unmute' : 'Mute'} onClick={call.toggleMuted} icon={call.muted ? <MicOff /> : <Mic />} /><Control label={call.cameraOn ? 'Camera' : 'Camera off'} onClick={call.toggleCamera} icon={call.cameraOn ? <Camera /> : <CameraOff />} /><Control label="Switch" onClick={() => void call.switchCamera()} icon={<RotateCcw />} /><Control label={call.speakerOn ? 'Speaker' : 'Quiet'} onClick={call.toggleSpeaker} icon={call.speakerOn ? <Volume2 /> : <VolumeX />} /><Control danger label="End" onClick={call.end} icon={<PhoneOff />} /></div>}
    </div>}
  </motion.div>}</AnimatePresence>
}
function Control({ icon, label, onClick, danger }: { icon: ReactNode; label: string; onClick: () => void; danger?: boolean }) { return <button onClick={onClick} className={`focus-ring grid h-14 min-w-14 place-items-center rounded-2xl p-2 text-xs ${danger ? 'bg-[#e76b7c] text-white' : 'bg-cream/15 text-cream backdrop-blur hover:bg-cream/25'}`} aria-label={label}>{icon}<span className="hidden sm:block">{label}</span></button> }
